### ISSUE TITLE
Node v0.12.x

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-cpp11#19]
We should drop 0.11.x, but start building 0.12.x.

To get there:

  - [x] node v0.12.x branch at https://github.com/mapbox/node (@springmeyer)
  - [x] apply patches to fix any remaining bugs with vs 2014/2015 (@springmeyer) - https://github.com/mapbox/node/pull/6
  - [ ] what improvements can be made to the build scripts here based on advances in aws ami scripting from @bsudekum?
  - [ ] Is the Visual Studio 2015 AMI ready? (I think @BergWerkGIS might have this working via the push to automate on AWS at https://github.com/mapbox/windows-builds)

**Comment by BergWerkGIS** [comment]
> Is the Visual Studio 2015 AMI ready?

Not quite there yet, but I hope to get everything into place this week.

**Comment by springmeyer** [comment]
closing - node v0.12.x builds are working now with the existing vs 2014 AMI. Good enough for this purpose for now.
