### ISSUE TITLE
Optimizing windows build

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-cpp11#20]
Seeing that the majority of time spent running the ec2 is just installing git: https://github.com/mapbox/node-cpp11/blob/master/cfn_build_node.userdata.bat#L3-L4. On the current instance I'm logged into after 34 minutes the `node-cpp11` folder has still not shown up (https://github.com/mapbox/node-cpp11/blob/master/cfn_build_node.userdata.bat#L6)

Starting to wonder if the firewall or network is misconfigured, causing downloads to take ages:

![screen shot 2015-02-23 at 12 55 43 pm](https://cloud.githubusercontent.com/assets/20300/6336980/7af777dc-bb5b-11e4-9813-8bce9b36a455.png)

**Comment by BergWerkGIS** [comment]
Noticed the same yesterday with `windows-builds`:

* 64bit build finished within expected time (30 -40 minutes)
* 32bit build (on same machine, ran right after the 64bit build) took 4hrs to complete

Don't know yet, what's causing this.
I've never experienced it when I was logged in and started a manual build.

**Comment by springmeyer** [comment]
Looks like in my case the `cinst git.install` was hung because the git installer process was still running. Killing the two git install processes allowed the backgrounded script to continue. This is what the task manager looked like before I killed the two git processes:
![screen shot 2015-02-23 at 1 03 47 pm](https://cloud.githubusercontent.com/assets/20300/6337144/a52cf31e-bb5c-11e4-9bf6-fb47ca889e19.png)

**Comment by springmeyer** [comment]
And then the instance ran for another few minutes and automatically shut down, which is odd because I started it with `[publish debug]` so I thought it would stay running.

**Comment by BergWerkGIS** [comment]
I remember we also had problems with `cinst` on AppVeyor.

**Comment by springmeyer** [comment]
@BergWerkGIS okay. So I think for your work over at https://github.com/mapbox/windows-builds we should consider pre-baking git and other tools in the AMI in order to avoid cinst needing to be run.

**Comment by springmeyer** [comment]
tried this to avoid git.install hang but did not work: https://github.com/mapbox/node-cpp11/commit/d9e075f5fbae592716e53ecf25be94baad83414f

We may be being hit by: https://groups.google.com/forum/#!msg/chocolatey/ewnCrG_q_bM/xeJZGDQIZMgJ

**Comment by springmeyer** [comment]
After much struggle, I figured out how to background the `cinst git.install`, use `timeout` to sleep a while, and then forcefully kill the git installer. With this in place the builds are now able to continue past this point!

**Comment by BergWerkGIS** [comment]
> we should consider pre-baking git and other tools in the AMI in order to avoid cinst needing to be run

y, that's the way I'm doing it.
VS, git, and Python installed on the AMI.
Everything else is just cloning or downloading and extracting.

BTW: VS2015 CTP6 is available since yesterday
http://www.visualstudio.com/downloads/visual-studio-2015-ctp-vs
Installing locally ATM.
