### ISSUE TITLE
Use AMI with visual studio 2015

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-cpp11#23]
Visual Studio 2015 is out (https://www.visualstudio.com/en-us/products/vs-2015-product-editions.aspx). We need to move to it immediately because its install breaks Visual Studio 2014 CTP 4 (which is currently in use).

refs https://github.com/mapbox/mapbox-studio/issues/1404

**Comment by springmeyer** [comment]
Steps to quickly fix this I think are:

  - [ ] New AMI that has vs 2015 installed (@bergwerkgis)
  - [ ] New branch of `cfn-ci` that uses that new AMI - https://github.com/mapbox/cfn-ci/blob/windows/ami/cfn-ami-win2012-vs2014.template#L28 (@yhahn helps)
  - [ ] Modify scripts to use correct path to vs 2015: https://github.com/mapbox/node-cpp11/blob/master/windows/settings.bat#L28-L39 (@springmeyer)
  - [ ] optional: use latest node versions (e.g. node v0.12.7 instead of v0.12.2) (@springmeyer)

**Comment by springmeyer** [comment]
Okay, v0.10.40 and v0.12.7 are now published based on vs 2015. Done I think and will merge #24 next!

**Comment by BergWerkGIS** [comment]
FYI: I've republished all the custom node versions, we had before:
additional to the ones above: 0.10.33, 0.10.36, 0.11.14, 0.12.0, 0.12.2.

**Comment by springmeyer** [comment]
:+1: @BergWerkGIS - hopefully just the latest will be needed, but good to have the others consistently using vs2015 to avoid surprises and in the rare case we might want to test older versions.
