### ISSUE TITLE
consider updating README

### ISSUE THREAD

**Issue by Mithgol** [mapbox/node-cpp11#27]
The README has never been touched since August 2015.

Since that time some new Node C++11 builds become available (such as v5.9.1), and newer Microsoft's redistributable Visual Studio 2015 installers (“update 2”) as well.

Consider updating README to reflect these news.

**Comment by springmeyer** [comment]
The upcoming node-mapnik release: v3.6.1 will work fine with the stock nodejs binaries. So this repo has been deprecated: https://github.com/mapbox/node-cpp11/blob/master/README.md#deprecated
