### ISSUE TITLE
Node.js v5 end-of-life day

### ISSUE THREAD

**Issue by Mithgol** [mapbox/node-cpp11#28]
Node.js v5 end-of-life day is happening, source: https://twitter.com/rvagg/status/748371867107467264

Consider releasing a newer NodeC++11 version (based on Node.js v6, with destructuring assignment and other cool new features) and a version of node-mapnik for it.

**Comment by springmeyer** [comment]
The upcoming node-mapnik release: v3.6.1 will work fine with the stock nodejs binaries. So this repo has been deprecated: https://github.com/mapbox/node-cpp11/blob/master/README.md#deprecated
