### ISSUE TITLE
Windows: link node against shared zlib

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-cpp11#6]
Ideally we want to link node.js dynamically against a shared zlib.dll to ensure the same exact zlib code is used by both node and any dependencies.

**Comment by springmeyer** [comment]
Now that we are able to build our own zlib 1.2.8 as a shared lib that works with libtiff (https://github.com/mapbox/mason/issues/7) the last step to ensure no invalid binary compatiblity is this ticket: building:

 - [ ] node against this same exact zlib
 - [ ] having node-zipfile use the same zlib too

**Comment by BergWerkGIS** [comment]
Sorry for not being precise enough: our own zlib is built static and shared successfully, but I haven't yet updated the libs (png, tif, gdal), that depend on it, to use the shared version.
The are still linking to the static version.

**Comment by springmeyer** [comment]
The upcoming node-mapnik release: v3.6.1 will work fine with the stock nodejs binaries. So this repo has been deprecated: https://github.com/mapbox/node-cpp11/blob/master/README.md#deprecated
